sudo: true

language: go

go:
  - "1.10.x"

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_lte-amd64
      - export VERSION=0.1.0
      - cd kubesim_lte
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goserv .
      - cd ..
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DHUBREPO:$VERSION -f images/kubesim_lte/Dockerfile .
      - docker images
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:latest
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DHUBREPO
    - stage: test
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_lte-amd64
      - export VERSION=0.1.0
      - docker run -d -p 127.0.0.1:8080:8080 --name hello $DHUBREPO:$VERSION
      - docker ps | grep -q hello
      - curl -vsf 'http://127.0.0.1:8080/index.html' &> /dev/stdout
